select * from (
SELECT 
OSTATKI.NM,
PRODUCER = '',
OSTATKI.QTY,
OSTATKI.SUM_OPT,
OSTATKI.SUM_ROZN,
PROD.PRODANO,
PROD.PRODANO_OPT,
PROD.PRODANO_ROZN
 FROM 
(SELECT 
V_GOODS_NAMES.NM,
QTY = SUM (V_REMAINS_ALL.QTY),
SUM_OPT =SUM (V_REMAINS_ALL.SUM_OPT),
SUM_ROZN = SUM (V_REMAINS_ALL.SUM_ROZN)
 FROM V_REMAINS_ALL , V_GOODS_NAMES
WHERE V_GOODS_NAMES.ID_GOODS = V_REMAINS_ALL.ID_GOODS
GROUP BY V_GOODS_NAMES.NM) AS OSTATKI LEFT OUTER JOIN (

SELECT
NM = V_GOODS_NAMES.NM,
 PRODANO =SUM  (V_CHEQUE_SUB.PRODANO),
 PRODANO_OPT = SUM (V_CHEQUE_SUB.SUM_PRODANO_OPT),
 PRODANO_ROZN = SUM (V_CHEQUE_SUB.SUM_PRODANO_ROZN) 
from V_CHEQUE_SUB , V_GOODS_NAMES
where V_CHEQUE_SUB.ID_GOODS = V_GOODS_NAMES.ID_GOODS
GROUP BY NM) AS PROD ON OSTATKI.NM = PROD.NM
union all

SELECT 
--OSTATKI.ID_GOODS,
V_GOODS_NAMES.NM,
PRODUCER = PRODUCER.NAME,
OSTATKI.QTY,
OSTATKI.SUM_OPT,
OSTATKI.SUM_ROZN,
PROD.PRODANO,
PROD.PRODANO_OPT,
PROD.PRODANO_ROZN
 FROM PRODUCER, GOODS,V_GOODS_NAMES,
(
SELECT 
V_REMAINS_ALL.id_goods,
QTY = SUM (V_REMAINS_ALL.QTY),
SUM_OPT =SUM (V_REMAINS_ALL.SUM_OPT),
SUM_ROZN = SUM (V_REMAINS_ALL.SUM_ROZN)
FROM V_REMAINS_ALL 
GROUP BY V_REMAINS_ALL.id_goods) AS OSTATKI LEFT OUTER JOIN (
SELECT
V_CHEQUE_SUB.id_goods,
 PRODANO =SUM  (V_CHEQUE_SUB.PRODANO),
 PRODANO_OPT = SUM (V_CHEQUE_SUB.SUM_PRODANO_OPT),
 PRODANO_ROZN = SUM (V_CHEQUE_SUB.SUM_PRODANO_ROZN) 
from V_CHEQUE_SUB
GROUP BY V_CHEQUE_SUB.ID_GOODS) AS PROD ON OSTATKI.ID_GOODS = PROD.ID_GOODS
where OSTATKI.ID_GOODS = GOODS.ID_GOODS and GOODS.ID_PRODUCER = PRODUCER.ID_PRODUCER
and OSTATKI.ID_GOODS = V_GOODS_NAMES.ID_GOODS
) as i
order by NM, PRODUCER




