
select  CASH_REGISTER.NAME_CASH_REGISTER as Kassa,  
goods.NAME as Tovar, PRODUCER.NAME as Proizv,
 SCALING_RATIO.DENOMINATOR as delitel, 
DATE_CHEQUE, QUANTITY as Kolvo,  lot.PRICE_SUP as CenaOpt,CHEQUE_ITEM.PRICE as CenaRozn, 
 CHEQUE_ITEM.SUMM as SumRozn, CHEQUE_ITEM.SUMM_DISCOUNT as SumSkidka
from CHEQUE_ITEM , CHEQUE , GOODS , LOT, CASH_REGISTER, CASH_SESSION , PRODUCER, SCALING_RATIO
where CHEQUE_ITEM.ID_CHEQUE_GLOBAL= CHEQUE.ID_CHEQUE_GLOBAL
and CHEQUE_ITEM.ID_GOODS = goods.ID_GOODS
and CHEQUE_ITEM.ID_GOODS = GOODS.ID_GOODS
and lot.ID_LOT_GLOBAL = CHEQUE_ITEM.ID_LOT_GLOBAL
and CHEQUE.ID_CASH_SESSION_GLOBAL = CASH_SESSION.ID_CASH_SESSION_GLOBAL
and CASH_SESSION.ID_CASH_REGISTER = CASH_REGISTER.ID_CASH_REGISTER
and goods.ID_PRODUCER = producer.ID_PRODUCER
and lot.ID_SCALING_RATIO = SCALING_RATIO.ID_SCALING_RATIO
and CHEQUE.DATE_CHEQUE between getdate ()-10 and GETDATE()


