IF OBJECT_ID('tempdb..#Results') IS NOT NULL
    DROP TABLE #Results
go
IF OBJECT_ID('tempdb..#LS') IS NOT NULL
    DROP TABLE #LS
go


SELECT        dbo.STORE.ID_STORE, lot.ID_GOODS ,  MAX(dbo.LOT_MOVEMENT.DATE_OP) AS POSLEDNEE_POSTUPLENIE
INTO #LS
FROM            dbo.LOT_MOVEMENT INNER JOIN
                         dbo.LOT ON dbo.LOT_MOVEMENT.ID_LOT_GLOBAL = dbo.LOT.ID_LOT_GLOBAL INNER JOIN
                         
                         dbo.STORE ON dbo.STORE.ID_STORE = dbo.LOT.ID_STORE
WHERE        (dbo.LOT_MOVEMENT.CODE_OP IN ('MOVE', 'INVOICE')) AND (dbo.LOT_MOVEMENT.OP = 'ADD')
GROUP BY dbo.STORE.ID_STORE, dbo.LOT.ID_GOODS


/*
CREATE TABLE #Results
(
SKLAD varchar (50),
APTEKA varchar(50),
ID_STORE int,
ID_GOODS int,
NM varchar(150), 
PRODUCER varchar(150), 
QTY float, 
SUM_OPT float, 
SUM_ROZN float, 
PRODANO float, 
SUM_PRODANO_OPT float,
SUM_PRODANO_ROZN float, 
OSTATOK_SKLAD float, 
SUM_OPT_SKLAD float, 
SUM_ROZN_SKLAD float,
QTY_MARK float,
ON_THE_WAY float
)
*/
SELECT        
dbo.STORE.NAME AS SKLAD,
dbo.CONTRACTOR.NAME as APTEKA,
dbo.V_REMAINS_ALL.ID_STORE,
dbo.V_REMAINS_ALL.ID_GOODS,
dbo.V_GOODS_NAMES.NM, 
dbo.V_GOODS_NAMES.PRODUCER, 
dbo.V_REMAINS_ALL.QTY, 
dbo.V_REMAINS_ALL.SUM_OPT, 
dbo.V_REMAINS_ALL.SUM_ROZN, 
dbo.V_CHEQUE_SUB.PRODANO, 
dbo.V_CHEQUE_SUB.SUM_PRODANO_OPT, 
dbo.V_CHEQUE_SUB.SUM_PRODANO_ROZN, 
dbo.V_REMAINS_SKLAD.QTY AS OSTATOK_SKLAD, 
dbo.V_REMAINS_SKLAD.SUM_OPT AS SUM_OPT_SKLAD, 
dbo.V_REMAINS_SKLAD.SUM_ROZN AS SUM_ROZN_SKLAD,
dbo.V_REMAINS_SKLAD_MARK.QTY as QTY_MARK,
DBO.V_REMAINS_ON_THE_WAY.ON_THE_WAY, 
#LS.POSLEDNEE_POSTUPLENIE
INTO #Results
FROM            dbo.V_REMAINS_ALL  LEFT OUTER JOIN
dbo.STORE ON dbo.V_REMAINS_ALL.ID_STORE = dbo.STORE.ID_STORE LEFT OUTER JOIN
dbo.V_GOODS_NAMES ON dbo.V_REMAINS_ALL.ID_GOODS = dbo.V_GOODS_NAMES.ID_GOODS LEFT OUTER JOIN
dbo.V_REMAINS_SKLAD ON dbo.V_REMAINS_ALL.ID_GOODS = dbo.V_REMAINS_SKLAD.ID_GOODS LEFT OUTER JOIN
dbo.V_CHEQUE_SUB ON dbo.V_REMAINS_ALL.ID_GOODS = dbo.V_CHEQUE_SUB.ID_GOODS 
AND dbo.V_REMAINS_ALL.ID_STORE = dbo.V_CHEQUE_SUB.ID_STORE LEFT OUTER JOIN 
dbo.CONTRACTOR ON dbo.store.ID_CONTRACTOR =   dbo.CONTRACTOR.ID_CONTRACTOR LEFT OUTER JOIN
DBO.V_REMAINS_SKLAD_MARK ON dbo.STORE.ID_STORE = V_REMAINS_SKLAD_MARK.ID_STORE 
and V_REMAINS_ALL.ID_GOODS = V_REMAINS_SKLAD_MARK.ID_GOODS LEFT OUTER JOIN 
V_REMAINS_ON_THE_WAY ON V_REMAINS_ALL.ID_GOODS = V_REMAINS_ON_THE_WAY.ID_GOODS 
AND V_REMAINS_ALL.ID_STORE = V_REMAINS_ON_THE_WAY.ID_STORE LEFT OUTER JOIN
#LS ON V_REMAINS_ALL.ID_GOODS = #LS.ID_GOODS and V_REMAINS_ALL.ID_STORE = #LS.ID_STORE
where dbo.store.NAME not like '%мин%ас%'



--- в остатках аптеки нет минимального ассортимента 
select  
NM , 
APTEKA ,
sum (QTY) as QTY, 
sum (SUM_OPT) as SUM_OPT , 
sum (SUM_ROZN) as SUM_ROZN, 
isnull ( sum (PRODANO),0) as PRODANO, 
isnull (sum (SUM_PRODANO_OPT),0) as SUM_PRODANO_OPT ,
isnull (sum (SUM_PRODANO_ROZN),0) as SUM_PRODANO_ROZN , 
isnull (sum (OSTATOK_SKLAD),0) as  OSTATOK_SKLAD, 
isnull (sum (SUM_OPT_SKLAD),0) as SUM_OPT_SKLAD , 
isnull (sum (SUM_ROZN_SKLAD),0) as SUM_ROZN_SKLAD ,
isnull (sum (QTY_MARK),0) as QTY_MARK ,
isnull (sum (ON_THE_WAY),0) as ON_THE_WAY ,
max (POSLEDNEE_POSTUPLENIE) as POSLEDNEE_POSTUPLENIE
from #Results
group by APTEKA, NM
order by APTEKA, NM

