IF OBJECT_ID('tempdb..#V_GOODS_NAMES') IS NOT NULL
    DROP TABLE #V_GOODS_NAMES

IF OBJECT_ID('tempdb..#V_REMAINS_ALL') IS NOT NULL
    DROP TABLE #V_REMAINS_ALL

IF OBJECT_ID('tempdb..#V_REMAINS_ALL_MA') IS NOT NULL
    DROP TABLE #V_REMAINS_ALL_MA


IF OBJECT_ID('tempdb..#V_REMAINS_ON_THE_WAY') IS NOT NULL
    DROP TABLE #V_REMAINS_ON_THE_WAY

IF OBJECT_ID('tempdb..#V_CHEQUE_SUB') IS NOT NULL
    DROP TABLE #V_CHEQUE_SUB


-- сопоставление имен для привязки и остальных
select V_GOODS_NAMES.ID_GOODS,V_GOODS_NAMES.NAME,V_GOODS_NAMES.NM
into #V_GOODS_NAMES
from V_GOODS_NAMES

--остатки минимальный ассортимент
select #V_GOODS_NAMES.NM,
--CONTRACTOR.NAME as APTEKA,
sum (V_REMAINS_ALL.QTY) as QTY,
sum (V_REMAINS_ALL.SUM_OPT) as SUM_OPT,
sum (V_REMAINS_ALL.SUM_ROZN) as SUM_ROZN
into #V_REMAINS_ALL_MA
from V_REMAINS_ALL, #V_GOODS_NAMES, STORE, CONTRACTOR
where V_REMAINS_ALL.ID_GOODS = #V_GOODS_NAMES.ID_GOODS
and STORE.ID_STORE = V_REMAINS_ALL.ID_STORE
and CONTRACTOR.ID_CONTRACTOR = store.ID_CONTRACTOR
and V_REMAINS_ALL.ID_STORE  in (select ID_STORE from store where store.NAME  like '%мин%ас%') -- убираем минимальный ассортимент
group by #V_GOODS_NAMES.NM --, CONTRACTOR.NAME 


--остатки все без минимального ассортимента
select #V_GOODS_NAMES.NM,
--CONTRACTOR.NAME as APTEKA,
sum (V_REMAINS_ALL.QTY) as QTY,
sum (V_REMAINS_ALL.SUM_OPT) as SUM_OPT,
sum (V_REMAINS_ALL.SUM_ROZN) as SUM_ROZN
into #V_REMAINS_ALL
from V_REMAINS_ALL, #V_GOODS_NAMES, STORE, CONTRACTOR
where V_REMAINS_ALL.ID_GOODS = #V_GOODS_NAMES.ID_GOODS
and STORE.ID_STORE = V_REMAINS_ALL.ID_STORE
and CONTRACTOR.ID_CONTRACTOR = store.ID_CONTRACTOR
and V_REMAINS_ALL.ID_STORE not in (select ID_STORE from store where store.NAME  like '%мин%ас%') -- убираем минимальный ассортимент
group by #V_GOODS_NAMES.NM --, CONTRACTOR.NAME 
----------------

--- продажи по чекам 
select 
--CONTRACTOR.NAME as APTEKA,
#V_GOODS_NAMES.NM,
sum (V_CHEQUE_SUB.PRODANO) as PRODANO,
sum (V_CHEQUE_SUB.SUM_PRODANO_OPT) as SUM_PRODANO_OPT,
sum (V_CHEQUE_SUB.SUM_PRODANO_ROZN) as SUM_PRODANO_ROZN
into #V_CHEQUE_SUB
from V_CHEQUE_SUB, CONTRACTOR, STORE, #V_GOODS_NAMES
where V_CHEQUE_SUB.ID_STORE = STORE.ID_STORE
and CONTRACTOR.ID_CONTRACTOR = STORE.ID_CONTRACTOR
and #V_GOODS_NAMES.ID_GOODS = V_CHEQUE_SUB.ID_GOODS
group by 
--CONTRACTOR.NAME,
#V_GOODS_NAMES.NM


select nm, 
sum (ON_THE_WAY ) as ON_THE_WAY
into #V_REMAINS_ON_THE_WAY
from V_REMAINS_ON_THE_WAY
group by NM


select 
#V_REMAINS_ALL.NM,
#V_REMAINS_ALL.QTY,
#V_REMAINS_ALL.SUM_OPT,
#V_REMAINS_ALL.SUM_ROZN,
#V_REMAINS_ALL_MA.QTY as QTY_MA,
#V_REMAINS_ALL_MA.SUM_OPT as SUM_OPT_MA,
#V_REMAINS_ALL_MA.SUM_ROZN as SUM_ROZN_MA,
#V_CHEQUE_SUB.PRODANO,
#V_CHEQUE_SUB.SUM_PRODANO_OPT,
#V_CHEQUE_SUB.SUM_PRODANO_ROZN,
#V_REMAINS_ON_THE_WAY.ON_THE_WAY

from 
#V_REMAINS_ALL Left OUTER JOIN 
#V_REMAINS_ALL_MA on #V_REMAINS_ALL.NM = #V_REMAINS_ALL_MA.NM left outer join 
#V_CHEQUE_SUB ON #V_REMAINS_ALL.NM = #V_CHEQUE_SUB.NM left outer join 
#V_REMAINS_ON_THE_WAY on #V_REMAINS_ALL.NM = #V_REMAINS_ON_THE_WAY.NM
order by #V_REMAINS_ALL.nm
