declare @doc varchar(30)
set @doc = '145033608-001' -- тут поставить номер документа поставщика

update KIZ
set CURRENT_STATE =1 
where ID_KIZ_GLOBAL in (

SELECT
    K.ID_KIZ_GLOBAL
	/*,
    II.ID_INVOICE_ITEM_GLOBAL,
    KIZ = K.BARCODE,
    K.GTIN_SGTIN,
    K.GTIN,
    K.SGTIN,
    K.TNVED4,
    K.BATCH,
    K.BEST_BEFORE,
    K.DATE_TO,
    K.ID_ERROR,
    KM.DOCUMENT_OUT_ID,
    II.ID_INVOICE_ITEM,
    II.ID_INVOICE,
    II.ID_INVOICE_GLOBAL,
    II.ID_GOODS,
    GOODS_NAME = G.NAME,
    GOODS_MNEMOCODE = G.MNEMOCODE,
    G.IMPORTANT,
    II.REGISTER_PRICE,
    G.MAX_PRICE_SAL,
    II.QUANTITY,
    II.ORDER_NUMBER,
    II.ID_SCALING_RATIO,
    SCALING_RATIO_NAME = ISNULL(SC.ALIAS, CAST(SC.NUMERATOR AS VARCHAR) + '/' + CAST(SC.DENOMINATOR AS VARCHAR) + ' ' + U.NAME),
    P.ID_PRODUCER,
    PRODUCER_NAME = P.NAME,
    COUNTRY_NAME = C.NAME,
    II.PRODUCER_PRICE,
    II.SUPPLIER_VAT_PER_UNIT,
    II.SUPPLIER_ADPRICE,
    II.SUPPLIER_PRICE,
    II.SUPPLIER_VAT,
    II.SUPPLIER_PRICE_VAT,
    II.SUPPLIER_SUM,
    II.SUPPLIER_VAT_SUM,
    II.SUPPLIER_SUM_VAT,
    II.RETAIL_ADPRICE,
    II.RETAIL_PRICE,
    II.RETAIL_VAT,
    II.RETAIL_VAT_SUM,
    II.RETAIL_SUM,
    II.RETAIL_SUM_VAT,
    II.RETAIL_PRICE_VAT,
    II.GTD_NUMBER,
    II.BAR_CODE,
    II.BREAKAGE_QTY,
    II.WASTE_QTY,
    II.SHORTFALL_QTY,
    II.OTHER_QTY,
    II.ID_GOS_CONTRACT_GOODS,
    II.BOX,
    GOODS_CODE = G.CODE,
    G.IS_WEIGHT,
	II.COST,
	II.ID_AUCTION_ORDER*/
FROM KIZ K(NOLOCK)
    INNER JOIN KIZ_2_DOCUMENT_ITEM KDI(NOLOCK) ON KDI.ID_KIZ_GLOBAL = K.ID_KIZ_GLOBAL
    INNER JOIN INVOICE_ITEM II(NOLOCK) ON II.ID_INVOICE_ITEM_GLOBAL = KDI.ID_DOCUMENT_ITEM_ADD
    INNER JOIN LOT L(NOLOCK) ON L.ID_LOT = (SELECT TOP 1 ID_LOT FROM LOT _L(NOLOCK) WHERE _L.ID_DOCUMENT = II.ID_INVOICE_GLOBAL AND _L.ID_DOCUMENT_ITEM = II.ID_INVOICE_ITEM_GLOBAL ORDER BY _L.ID_LOT ASC)
    INNER JOIN MV_GOODS G(NOLOCK) ON G.ID_GOODS = II.ID_GOODS
    INNER JOIN PRODUCER P(NOLOCK) ON G.ID_PRODUCER = P.ID_PRODUCER
    INNER JOIN SCALING_RATIO SC(NOLOCK) ON ii.ID_SCALING_RATIO = SC.ID_SCALING_RATIO
    INNER JOIN UNIT U(NOLOCK) ON U.ID_UNIT = SC.ID_UNIT
    INNER JOIN COUNTRY C(NOLOCK) ON C.ID_COUNTRY = P.ID_COUNTRY
    LEFT JOIN KIZ_ITEM KI(NOLOCK) ON KI.ID_DOCUMENT = II.ID_INVOICE_GLOBAL AND KI.ID_DOCUMENT_ITEM = II.ID_INVOICE_ITEM_GLOBAL AND KI.ID_KIZ_GLOBAL = K.ID_KIZ_GLOBAL AND KI.ID_LOT_GLOBAL = L.ID_LOT_GLOBAL
    LEFT JOIN KIZ_MOVE KM(NOLOCK) ON KM.ID_KIZ_ITEM_GLOBAL = KI.ID_KIZ_ITEM_GLOBAL AND KM.ID_KIZ_MOVE = (SELECT TOP 1 ID_KIZ_MOVE FROM KIZ_MOVE _KM(NOLOCK) WHERE _KM.ID_KIZ_ITEM_GLOBAL = KI.ID_KIZ_ITEM_GLOBAL ORDER BY ID_KIZ_MOVE DESC)
WHERE II.ID_INVOICE_GLOBAL = 
(
select top 1 ID_INVOICE_GLOBAL from invoice 
where incoming_number = @doc and document_date between getdate()-30 and getdate()
and DOCUMENT_STATE = 'PROC'
)
)

